List<String> quotes = [
  "What's my age again?",
  "Life is either a daring adventure or nothing at all.",
  "Be yourself; everyone else is already taken.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "The only way to do great work is to love what you do.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Don't watch the clock; do what it does. Keep going.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "The best way to predict your future is to create it.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "Believe you can and you're halfway there.",
  "The purpose of our lives is to be happy.",
  "If you want to achieve greatness, stop asking for permission.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "In the middle of difficulty lies opportunity.",
  "The best revenge is massive success.",
  "You miss 100% of the shots you don't take.",
  "The only person you should try to be better than is the person you were yesterday.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The mind is everything. What you think you become.",
  "Do not wait for the opportunity. Create it.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are never too old to set another goal or to dream a new dream.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "You can't use up creativity. The more you use, the more you have.",
  "It always seems impossible until it's done.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "The only way to do great work is to love what you do.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "It is never too late to be what you might have been.",
  "The best revenge is massive success.",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "I would rather die of passion than of boredom.",
  "Believe you can and you're halfway there.",
  "The harder I work, the luckier I get.",
  "You become what you believe.",
  "The best dreams happen when you're awake.",
  "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.",
  "The difference between ordinary and extraordinary is that little extra.",
  "I find that the harder I work, the more luck I seem to have.",
  "There is no substitute for hard work.",
  "Don't watch the clock; do what it does. Keep going.",
  "Dream big and dare to fail.",
  "Life is too important to be taken seriously.",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks.",
  "Simplicity is the ultimate sophistication.",
  "The secret of getting ahead is getting started."
];
